### ISSUE TITLE
P1 – Getting Additional Users into Makestagram – Missing link?

### ISSUE THREAD

**Issue by jessetipton** [MakeSchool-Tutorials/Makestagram-Swift-Part2-V2#2]
Seems likes there should be a link after that colon.

<img width="679" alt="screen shot 2016-06-15 at 10 39 56 am" src="https://cloud.githubusercontent.com/assets/2132778/16090758/af79ad88-32e5-11e6-8fd4-1888ab10a516.png">

**Comment by danielhaaser** [comment]
Fixed in 41e184b0387b4856e44c4f0e5500201de14d82be
