### ISSUE TITLE
1. issue with markdown formatting

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Makestagram-Swift-Part2-V2#3]
In the section "Getting Additional Users into Makestagram", the following part of the screenshot should probably be rendered as a list with increasing numbers

<img width="780" alt="screen shot 2016-06-15 at 14 30 51" src="https://cloud.githubusercontent.com/assets/4058327/16098018/da4b66ee-3305-11e6-8534-8ea5b5ab65bf.png">

**Comment by danielhaaser** [comment]
Fixed in 41e184b0387b4856e44c4f0e5500201de14d82be
